### ISSUE TITLE
Use appimagetool or linuxdeployqt

### ISSUE THREAD

**Issue by probonopd** [groupgets/GetThermal#1]
Hi, I noticed you are using AppImageAssistant. It has been replaced by `appimagetool`. Overall an approach using [Travis CI](https://travis-ci.org) and then bundling the build artifacts like in [these examples](https://github.com/search?q=%22Package+the+binaries+built+on+Travis-CI+as+an+AppImage%22&type=Code&utf8=✓) (using `functions.sh` which abstracts away all the hard work) seems easiest to me.

When you use `generate_type2_appimage`instead of `generate_appimage`, then `appimagetool` is automatically used in the process.

For Qt applications, [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) might also be worth a try. These projects are already using [Travis CI](http://travis-ci.org/) and linuxdeployqt to provide AppImages of their builds:

- https://github.com/Blinkinlabs/PatternPaint
- https://github.com/fathomssen/redtimer
- https://github.com/coryo/amphetype2
- https://github.com/chkmue/MyQtTravisTemplateProject
- https://github.com/chkmue/qttravisCI_1
- https://github.com/eteran/edb-debugger

**Comment by kekiefer** [comment]
Changed deployment method to use linuxdeployqt with c3a8ed043193afab887759da9d0fc9e71d7bd7e1
