### ISSUE TITLE
NVIDIA TX2 + Boson 320 

### ISSUE THREAD

**Issue by mipsan** [groupgets/GetThermal#10]
![error1_getthermal](https://user-images.githubusercontent.com/3205851/43874643-e8a1c576-9bc7-11e8-926e-88bc1103328b.png)
![error2_getthermal](https://user-images.githubusercontent.com/3205851/43874644-e8dc6eec-9bc7-11e8-84a5-5ce6c647b330.png)

Hello,

I built GetThermal for NVIDIA TX2, running Ubuntu 16.04(x64) and Qt 5.9.5.
When start as a normal account, it cannot display video.
But as a sudo, it cannot show gage.

I attach screenshots as follow, and wait for any helpful advice.
Thanks,

**Comment by kekiefer** [comment]
If you want to run as a non-root user, that user needs to have permissions to access the camera.

Is your camera a radiometric part Lepton 2.5 or 3.5? If not then you won't see that temperature gauge.

**Comment by mipsan** [comment]
Very Thanks Kekiefer,
