### ISSUE TITLE
Lepton 3.5 with PT1 windows?

### ISSUE THREAD

**Issue by Thanh-Binh** [groupgets/GetThermal#15]
I have Lepton 3.5 + PT1 Board and want to work in Windows.

Have anybody a SW for windows?
Thanks for help

**Comment by kekiefer** [comment]
FLIR's official Lepton SDK and viewer app support the PT1/PT2 on Windows: https://lepton.flir.com

**Comment by Thanh-Binh** [comment]
Thanks.

**Comment by Thanh-Binh** [comment]
Unfortunately, this is no Sdk in the right sense. I need lib for building in c++ application in windows
