### ISSUE TITLE
v4l2 stream error: cannot open device '/dev/video0'

### ISSUE THREAD

**Issue by tmsd2001** [groupgets/GetThermal#17]
I have a PureThermal 2 with Lepton 3.5. Windows 10 VLC play the video stream, on Ubuntu 18.04 VLC can't play, the log show "v4l2 stream error: cannot open device '/dev/video0': Operation not permitted" and "audit: type=1400 audit(1553403072.607:47): apparmor="DENIED" operation="ptrace" profile="snap.v
lc.vlc" pid=2176 comm="vlc" requested_mask="trace" denied_mask="trace" peer="unconfined"".
Permision of /dev/video0 und /dev/bus/usb... is set to my username.

**Comment by kekiefer** [comment]
General v4l2 support is not in the scope of the GetThermal project, which doesn't even use v4l2.

**Comment by tmsd2001** [comment]
OK, you say v4l2 is not in the scope, but this is the Video device PureThermal 2 install in Ubuntu. Or how can I stream the PureThermal 2 board in Ubuntu?

**Comment by kekiefer** [comment]
You can find some examples for capturing data somewhere else: https://github.com/groupgets/purethermal1-uvc-capture

Or you can consult the Flir Lepton google group: https://groups.google.com/forum/#!forum/flir-lepton
