### ISSUE TITLE
How can we get the Thermal stream for deep learning module?

### ISSUE THREAD

**Issue by spk921** [groupgets/GetThermal#18]
I would like to get the Thermal stream as deep learning model input. 
What is the best way to get the Thermal stream?

**Comment by kekiefer** [comment]
https://bitbucket.org/groupgets/pure-thermal-examples

**Comment by spk921** [comment]
@kekiefer Thank you but the bitbucket is denied and can't see the examples.

**Comment by kekiefer** [comment]
My mistake, the repository moved here https://github.com/groupgets/purethermal1-uvc-capture

**Comment by spk921** [comment]
@kekiefer  It only has python script working on Lepton3.5. How could I get working Lepton3.5 with C++ application? Is there are GetThermal CMakeList version?
