### ISSUE TITLE
depends on non-NOTIFYable propertie, TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by gisulee-mr** [groupgets/GetThermal#19]
hello!

![image](https://user-images.githubusercontent.com/37143542/56645298-6077f280-66b8-11e9-81b8-63acace03e02.png)

I would like a color graph.
i have a problem like the picture. Please tell me how to fix it

**Comment by kekiefer** [comment]
If you don't have a radiometric lepton, that graph won't show up.

**Comment by gisulee-mr** [comment]
![Screenshot from 2019-04-25 10-17-04](https://user-images.githubusercontent.com/37143542/56703362-649d2200-6743-11e9-8573-31996a38394a.png)

Is it related to GPP, DSP, PT1 FW version?

How do I use my radiometric lepton?

**Comment by kekiefer** [comment]
500-0726-01 is a Lepton 3.0. Lepton 2.5 and 3.5 are the radiometric parts.
