### ISSUE TITLE
Radiometry on Boson isn't obvious, switch to hw color mode and suppor… 

### ISSUE THREAD

**Issue by moscamich** [groupgets/GetThermal#2]
Hi, 

great work ported and run also on Jetson NVidia TX1.
not sure I understand your comment on Getthermal.pro - radiomentry of boson:
Radiometry on Boson isn't obvious, switch to hw color mode and suppor… 

what do you mean? how to switch to hw color? if so why did not force it in the code :) 
is it a sort of mimic radiometry with boson?

thanks
mm

**Comment by kekiefer** [comment]
This means I couldn't figure out how to get radiometry to work on the Boson, even though the IR16 data type could be acquired. The commit you're referring to switched to using the hardware pseudo-color image instead.
