### ISSUE TITLE
PureThermal mini

### ISSUE THREAD

**Issue by CubeSatboi** [groupgets/GetThermal#27]
I have been trying to use this with the PureThermal mini, I know that it doesn't specify compatibility with this version of the PureThermal board. But I thought it may anyway because they're both made by GroupGets.

**Comment by CubeSatboi** [comment]
Should have mentioned that I haven't gotten it to work

**Comment by kekiefer** [comment]
It should work the same as any other PureThermal board.

**Comment by LazyEngineerToBe** [comment]
I can confirm that the software works with the PureThermal Mini

**Comment by kekiefer** [comment]
Has this issue been resolved?

**Comment by CubeSatboi** [comment]
It wasn’t tested because we got the pure thermal 2 instead
