### ISSUE TITLE
Lepton Camera feed not available

### ISSUE THREAD

**Issue by prat96** [groupgets/GetThermal#3]
Hi all,

Am not getting any video feed from the Lepton although the app is running. Please advise.

Output from QT 5.7:

Starting /home/prat96/Error in " Util.asciify("build-GetThermal-Desktop_Qt_5_7_1_GCC_64bit-Debug")": TypeError: Property 'asciify' of object Core::Internal::UtilsJsExtension(0xd2be10) is not a function/debug/GetThermal...
QML debugging is enabled. Only use this in a safe environment.
uvc_open
: Access denied (-3)
UVC initialized
Device found
Surface set. Supported formats: 18 19 22 23 3 1 10 8 5
Surface supports format 0 width -1 height -1qrc:/lepton/AgcControls.qml:276: TypeError: Type error
qrc:/lepton/AgcControls.qml:268: TypeError: Type error
qrc:/lepton/VidControls.qml:85: TypeError: Type error
qrc:/lepton/VidControls.qml:41: TypeError: Cannot read property 'vidPcolorLut' of null
qrc:/lepton/VidControls.qml:26: TypeError: Cannot read property 'supportsHwPseudoColor' of null
qrc:/lepton/VidControls.qml:47: TypeError: Cannot read property 'supportsHwPseudoColor' of null
qrc:/lepton/VidControls.qml:63: TypeError: Cannot read property 'vidSbNucEnableState' of null
qrc:/lepton/AgcControls.qml:11: TypeError: Cannot read property 'supportsRadiometry' of null
qrc:/lepton/AgcControls.qml:23: TypeError: Cannot read property 'agcEnable' of null
qrc:/lepton/AgcControls.qml:31: TypeError: Cannot read property 'agcCalcEnable' of null
qrc:/lepton/AgcControls.qml:53: TypeError: Cannot read property 'agcPolicy' of null
qrc:/lepton/AgcControls.qml:168: TypeError: Cannot read property 'agcHeqScaleFactor' of null
qrc:/lepton/InfoControls.qml:31: TypeError: Cannot read property 'oemFlirPartNumber' of null
qrc:/lepton/InfoControls.qml:36: TypeError: Cannot read property 'sysFlirSerialNumber' of null
qrc:/lepton/InfoControls.qml:41: TypeError: Cannot read property 'oemGppSoftwareVersion' of null
qrc:/lepton/InfoControls.qml:46: TypeError: Cannot read property 'oemDspSoftwareVersion' of null
qrc:/lepton/InfoControls.qml:51: TypeError: Cannot read property 'ptFirmwareVersion' of null
qrc:/ViewerForm.ui.qml:61: TypeError: Cannot read property 'supportsRadiometry' of null
UVC exited
/home/prat96/Error in " Util.asciify("build-GetThermal-Desktop_Qt_5_7_1_GCC_64bit-Debug")": TypeError: Property 'asciify' of object Core::Internal::UtilsJsExtension(0xd2be10) is not a function/debug/GetThermal exited with code 0

**Comment by kekiefer** [comment]
Your user needs to have access to the USB device. You can either add a UDEV rule for this or run the program as root. Here's a command to create a UDEV rule to allow full access to all users of the PT1:

```
sudo sh -c "echo 'SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"1e4e\", ATTRS{idProduct}==\"0100\", SYMLINK+=\"pt1\", GROUP=\"usb\", MODE=\"666\"' > /etc/udev/rules.d/99-pt1.rules"
```

**Comment by prat96** [comment]
@kekiefer Thank you! This worked after a fresh build of GetThermal and a reboot. 

However, now I am not able to acces any of the AGC options in app. They are all greyed out.

**Comment by kekiefer** [comment]
If the AGC options are grayed out, you might check if you have Y16 firmware on your PT1 (which is required to use radiometry of the PT1). In radiometric mode, you can't use the hardware AGC (which is what that tab sets up).

As for missing features, yes those would be great things to have. I'm just one developer who hasn't had much time to work on this application, which is simply a work in progress I decided to publish. If you're capable, of course pull requests are welcome.

**Comment by prat96** [comment]
@kekiefer Aah alright, will definitely work on this. Thanks :)

**Comment by spk921** [comment]
@kekiefer  Is this same as the Purthurmal2? 

```
sudo sh -c "echo 'SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"1e4e\", ATTRS{idProduct}==\"0100\", SYMLINK+=\"pt1\", GROUP=\"usb\", MODE=\"666\"' > /etc/udev/rules.d/99-pt1.rules"
```
