### ISSUE TITLE
recipe for target 'release/GetThermal' failed

### ISSUE THREAD

**Issue by Varat7v2** [groupgets/GetThermal#30]
Hi I am trying to install GetThermal in Ubuntu 18.04. I installed everything but the `make` command for .../GetThermal/build is throwing following error. I could not find any solution for it.

> /usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:274: recipe for target 'release/GetThermal' failed
make: *** [release/GetThermal] Error 1

Any kind of suggestions / references will be helpful to me.
Thank you.

**Comment by Varat7v2** [comment]
Now I can see the video but temperature bar is not visible. How can I make it visible?

**Comment by kekiefer** [comment]
The temperature bar is only visible for radiometric parts, Lepton 2.5 and 3.5. Do you have one of these parts?

**Comment by Varat7v2** [comment]
No mine one is Lepton 3.0. 

Thank you.
