### ISSUE TITLE
minPoint and maxPoint not properly mapped in dataformatter.cpp

### ISSUE THREAD

**Issue by qusvv** [groupgets/GetThermal#34]
https://github.com/groupgets/GetThermal/blob/661a519a43a9c150ae1de487e50b60db7ce8306c/src/dataformatter.cpp#L47-L72

`i` sweeps through the input's height (y direction) and `j` its width (x)

values passed to setX() and setY() should then be inverted

Thanks!

**Comment by kekiefer** [comment]
It looks like you're right, could you send a pull request?

**Comment by qusvv** [comment]
OK, will do. Should I add a Q_PROPERTY and plot maxPoint in the UI as a validation?
qynn



Sep. 24, 2020, 6:27 p.m. by notifications@github.com:

**Comment by kekiefer** [comment]
Sure, that would be great!

**Comment by kekiefer** [comment]
Closed via #35
