### ISSUE TITLE
Please release Windows version

### ISSUE THREAD

**Issue by Videogamer555** [groupgets/GetThermal#37]
My PC is running Windows, not Linux. Please compile a Windows version for me. I'm considering buying the FLIR 3.5 with a USB interface board, and I need Windows software to use it. I won't buy it if I can't use it.

**Comment by kekiefer** [comment]
For Windows support, the purethermal boards are fully supported by the official FLIR Lepton Windows app and SDK:
https://lepton.flir.com/lepton-and-windows

An alternative open source viewer for Windows is the MediaFoundation example found here:
https://github.com/groupgets/purethermal1-uvc-capture
