### ISSUE TITLE
Thermal Image not loading

### ISSUE THREAD

**Issue by StellaLH** [groupgets/GetThermal#4]
I've followed all the instructions for building GetThermal with a Raspberry Pi and the GetThermal window opens.

However, the thermal image is missing when I do so. I've probably missed something simple, but was wondering if you have any advice?
![2017-07-05-134318_1920x1080_scrot](https://user-images.githubusercontent.com/29922061/27868065-22f303ac-618b-11e7-8342-38448754d82e.png)

**Comment by kekiefer** [comment]
`uvc_find_device` is returning an error "No such device". Is the camera plugged in and turned on, and do you see it listed when you run `lsusb`?

**Comment by hunter-hunter** [comment]
Don't know if you have already solved this but I had the same problem but it worked for me running ./GetThermal as sudo.

**Comment by vancanwin** [comment]
> I've followed all the instructions for building GetThermal with a Raspberry Pi and the GetThermal window opens.
> 
> However, the thermal image is missing when I do so. I've probably missed something simple, but was wondering if you have any advice?
> ![2017-07-05-134318_1920x1080_scrot](https://user-images.githubusercontent.com/29922061/27868065-22f303ac-618b-11e7-8342-38448754d82e.png)

I'm getting the same issues still.  How did you fix it?  Running ./GetThermal as sudo did not work for me.

**Comment by Kheirlb** [comment]
Sometimes the lepton pops out of the PureThermal2 camera socket just a hair and causes a similar issue for me. Pull out the lepton and re-insert it into the socket.

**Comment by apolo74** [comment]
Hi all, this is an old post but I hope somebody here can give me any news on how to solve this problem. I'm working with Ubuntu Linux 18.04 and Flir Lepton 3.5 + PureThermal 2. I followed all instructions for building libuvc and GetThermal but I'm getting the same error as reported in here. I understand the camera is not being detected but I don't know how I'm supposed to solve that since the camera is just a USB cable connected to the PureThermal2. The camera seems to be working since the small led is blinking from the moment I connect the cable.

**Comment by hunter-hunter** [comment]
Does the result of `lsusb` tell you that your computer sees the USB device? You can also try unplugging the camera, run `dmesg -w` and then plug the camera back in to see if that gives you any hints. I don't have access to this equipment any longer so my help will probably be limited

**Comment by apolo74** [comment]
I found the problem to be the USB cable I was using to connect the camera. I changed the cable and now I the camera is recognized. Thanks for your help

**Comment by ajfarkas** [comment]
@apolo74 What kind of cable did you change to? I'm having the same problem and have gone through several cables already.
