### ISSUE TITLE
Does not run on Ubuntu trusty

### ISSUE THREAD

**Issue by probonopd** [groupgets/GetThermal#6]
The GetThermal AppImage is not running on Ubuntu trusty, possibly it was built on a build host that was newer than Ubuntu trusty, which pulls in "too recent" dependencies on core system libraries such as libstdc++.

Error log:
https://travis-ci.org/AppImage/appimage.github.io/builds/287151543#L713-L728

Would it be possible to build the AppImage on Ubuntu trusty or earlier?

**Comment by kekiefer** [comment]
Bummer. This was built on a Debian 9 machine. I'll look into a better build solution like you say.

**Comment by MarianoMunoz** [comment]
Just a note, but the AppImage does not run on 64bit Ubuntu 17.05 (Zesty Zapus) either.

**Comment by kekiefer** [comment]
The most recent AppImage builds are being created by Travis in a Trusty VM and should be more compatible.
